project:
  type: book
  output-dir: docs

engine: knitr

book:
  title: "R语言数据可视化学习笔记"
  language: zh
  reader-mode: true

  page-footer:
    center: |
      博客<a href="https://blog.stariverfeel.eu.org/">Feel's Blog</a> | 部署 <a href="https://quarto.org/">Quarto</a>.
  favicon: "favicon.png"
  cover-image: "logo.png"
  site-url: https://bookr.stariverfeel.eu.org/
  repo-url: https://github.com/FeelLiao/RdataVisualization
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - ChangeLog.qmd

    - part: ggplot2/ggplot2chapter.qmd
      chapters: 
        - ggplot2/ggplot2intro.qmd
        - ggplot2/ggplot2internal.qmd
        - ggplot2/ggplot2extend.qmd
        - ggplot2/ggplot2_spring.qmd

    - part: plot/plot_ex.qmd
      chapters: 
        - plot/top50en.qmd
        - plot/top50zh.qmd
        - plot/BasicStatisticalGraph.qmd
        - plot/NetworkRelatedGraph.qmd

    - part: extension/extension_chapter.qmd
      chapters: 
        - extension/gghdr.qmd
        - extension/introdataviz.qmd

format:
  html:
    theme:
      - cosmo
    code-link: true

    author-meta: "Feel Liao"
    callout-appearance: simple


editor: visual